FROM node:20-bullseye

WORKDIR /app

ARG VITE_LOCAL_AUTH_ENABLED
ARG VITE_APP_ID
ARG VITE_OAUTH_PORTAL_URL
ARG VITE_FRONTEND_FORGE_API_KEY
ARG VITE_FRONTEND_FORGE_API_URL

ENV VITE_LOCAL_AUTH_ENABLED=$VITE_LOCAL_AUTH_ENABLED
ENV VITE_APP_ID=$VITE_APP_ID
ENV VITE_OAUTH_PORTAL_URL=$VITE_OAUTH_PORTAL_URL
ENV VITE_FRONTEND_FORGE_API_KEY=$VITE_FRONTEND_FORGE_API_KEY
ENV VITE_FRONTEND_FORGE_API_URL=$VITE_FRONTEND_FORGE_API_URL

ENV NODE_ENV=production
ENV UPLOADS_DIR=/app/uploads

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
COPY patches ./patches

RUN pnpm install --no-frozen-lockfile

COPY . .

RUN mkdir -p /app/uploads

ARG VITE_GA4_ID
ARG VITE_META_PIXEL_ID

ENV VITE_GA4_ID=$VITE_GA4_ID
ENV VITE_META_PIXEL_ID=$VITE_META_PIXEL_ID

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]